language: node_js
node_js:
  - '10'
  - '12'
  - 'lts/*'
branches:
  only:
    - master
before_install:
  - pip install --user codecov
install:
  - npm install
script:
  - npm test
after_success:
  - codecov --file coverage/lcov.info --disable search