name: Run Tests and Generate CodeCov Report
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [10.x, 12.x, 14.x]
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v2
      - name: Setup Python (pip)
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install CodeCov for Coverage Reports
        run: pip install --user codecov
      - name: Install Project Dependencies
        run: npm install
      - name: Run Unit Tests and Generate Coverage Report
        run: npm test
      - name: Upload Coverage Report to codecov.io
        run: codecov --file coverage/lcov.info --disable search
